// Core brief and export controls are intentionally dependency-free. PDF.js is only
// loaded if a report is selected, so an unavailable CDN can never blank the brief.
let pdfjsLib;
async function getPdfJs(){
  if(pdfjsLib) return pdfjsLib;
  if(!window.pdfjsLib){
    await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});
  }
  pdfjsLib=window.pdfjsLib;
  if(!pdfjsLib) throw new Error('PDF reader could not load');
  pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
  return pdfjsLib;
}

const sources={
  S1:{name:'Statistics Korea, “December 2024 and Annual Online Shopping Trends”',where:'Annual results release, 4 Feb 2025; annual headline/table (Korean)',url:'https://www.kostat.go.kr/board.es?act=view&bid=241&list_no=434934&mid=a10301120100'},
  S2:{name:'Coupang, Inc., 2025 Form 10-K',where:'Item 1 Business, pp. 4-6; Item 1A Risk Factors, pp. 15-18, 35; Item 1C Cybersecurity, p. 44; Item 7 MD&A, pp. 47-50.',url:'https://www.sec.gov/Archives/edgar/data/1834584/000183458426000024/cpng-20251231.htm'},
  S3:{name:'Coupang, Inc., 2025 Form 10-K',where:'Key Business Metrics, p. 49; Results of Operations, p. 50.',url:'https://www.sec.gov/Archives/edgar/data/1834584/000183458426000024/cpng-20251231.htm'},
  S4:{name:'Shinsegae, business report (Korea Exchange disclosure)',where:'Industry overview: reports KFTC 2022 e-commerce shares for Coupang, Naver, and combined SSG.com/Gmarket.',url:'https://kind.krx.co.kr/external/2026/01/21/000083/20260121000127/10601.htm'},
  S5:{name:'Korea Fair Trade Commission case summary via KDI',where:'14 Jun 2024 release: alleged manipulation of search ranking (“Coupang Ranking”); 140 billion won administrative fine and corrective order.',url:'https://eiec.kdi.re.kr/policy/materialView.do?num=252663&pg=&pp=&topic=P'},
  S6:{name:'Korea Development Institute, “Online Retail Growth and Reforming Korea’s Retail Policy”',where:'Market structure section; January 2024 payment-value comparison across 16 major online platforms.',url:'https://m.kdi.re.kr/eng/research/focusView?pub_no=19240'},
  S7:{name:'U.S. Census Bureau, 2022 NAICS Manual',where:'Code 454110, Electronic Shopping and Mail-Order Houses — retailing merchandise using electronic means.',url:'https://www.census.gov/naics/'},
};
const brief={company:'Coupang',market:'South Korea',date:'Evidence reviewed through 25 Feb 2025 filings and 4 Feb 2025 market release',industry:'South Korean e-commerce retailing',naics:'454110 — Electronic Shopping and Mail-Order Houses',naicsWhy:'Coupang’s core activity is retailing merchandise through apps and websites. We use 454110 rather than 493110 (General Warehousing and Storage) because Rocket logistics enables the retail offer; it is not the primary activity being analyzed.',scope:'Coupang operates in several adjacent businesses—fulfillment/logistics, Coupang Eats, fintech, advertising, streaming, international operations, and Farfetch. For this project, the industry cut is its South Korean e-commerce retailing business: first-party online retail plus marketplace activity. Adjacent businesses are only noted where they affect that industry.',signals:[
 {title:'Industry size & trajectory',text:'South Korean online-shopping transaction value was ₩242.1 trillion in 2024, up 5.8% year over year. The annual growth rate slowed from 20.2% (2021) to 10.3% (2022), 8.3% (2023), and 5.8% (2024): a large, still-growing market with decelerating expansion.',cite:'S1'},
 {title:'Coupang scale',text:'Coupang reported $34.5 billion of 2025 consolidated revenue, up 14% year over year. Net retail sales were $26.3 billion, up 10%; Product Commerce active customers reached 24.6 million at December 31, 2025, up 8%. These are company measures, not an estimate of Korean industry GMV.',cite:'S3'},
 {title:'Regulatory / compliance pressure',text:'High. The 2025 10-K identifies Korean fair-trade and pricing, competition, labor, workplace-safety, privacy/data, consumer protection, advertising, trade, payments, and tax rules as material. It also reports the November 2025 unauthorized-access incident affecting approximately 33 million customer accounts and says it may lead to remediation, enforcement, and litigation costs.',cite:'S2'},
 {title:'Supply chain concentration / fragility',text:'Fragility is more evidenced than supplier concentration. Coupang depends on suppliers and marketplace merchants for timely, compliant inventory, and its fulfillment network needs facilities, frontline labor and delivery partners. The 10-K identifies disruption from disasters, weather, health events and labor conditions. I could not find a public supplier-concentration ratio.',cite:'S2'},
 {title:'Customer concentration / fragmentation',text:'Consumer demand is fragmented rather than account-concentrated: 24.6 million Product Commerce active customers each ordered at least once in the quarter and are identified by a unique email address. The filing does not report a top-customer concentration ratio, so no percentage is asserted.',cite:'S2; S3'},
 {title:'Biggest five-year trend',text:'Mobile-led convenience and fulfillment integration. Mobile represented 76.4% of December 2024 online-shopping transaction value, and food/grocery and food-delivery categories outgrew the total market. The implication is that frequency, delivery density and recurring household purchases matter more than simply adding online assortment.',cite:'S1'},
 {title:'Biggest five-year threat',text:'Margin pressure from aggressive platform competition, paired with heightened regulatory and cybersecurity exposure. The 10-K says competitors may price and market more aggressively and reports a customer-compensation program with approximately $1.2 billion of vouchers after the 2025 data incident. This is an analytical judgment, not a numeric forecast.',cite:'S2; S4'},
 ]};
const competitors=[['Coupang','24.5%','KFTC 2022 estimate reported in S4'],['Naver','23.3%','KFTC 2022 estimate reported in S4'],['SSG.com + Gmarket','11.5% combined','KFTC 2022 combined estimate reported in S4; individual shares not found'],['11st','Not found','Recognized competitor; no comparable public share found in reviewed sources'],['AliExpress / Temu','Not found','Competitive cross-border entrants; no comparable public 2022 share found in reviewed sources']];
let imported=[];
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function citation(ids){return `<span class="citation">Source: ${ids.split('; ').map(id=>`<a href="${sources[id].url}" target="_blank" rel="noopener">[${id}]</a> ${esc(sources[id].where)}`).join(' · ')}</span>`}
function render(){const b=brief;$('#brief').innerHTML=`
  <p class="eyebrow">STRUCTURED INDUSTRY BRIEF</p><h2>${esc(b.company)} — ${esc(b.industry)}</h2><p class="meta">Market: ${esc(b.market)} · ${esc(b.date)}</p>
  <p class="scope">${esc(b.scope)}</p><div class="naics"><strong>NAICS selection: ${esc(b.naics)}</strong>${esc(b.naicsWhy)}${citation('S7')}</div>
  <h3>Signals</h3><div class="signal-grid">${b.signals.map(x=>`<section class="signal"><h4>${esc(x.title)}</h4><p>${esc(x.text)}</p>${citation(x.cite)}</section>`).join('')}</div>
  <h3>Competitor map</h3><table class="competitors"><thead><tr><th>Platform</th><th>Share estimate</th><th>Evidence / limit</th></tr></thead><tbody>${competitors.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>${citation('S4')}
  <h3>Evidence gaps and what would close them</h3>
  <div class="gap"><strong>Supplier concentration:</strong> I don’t know a verified supplier concentration ratio. A current IBISWorld report or Coupang supplier/merchant disclosure with a top-supplier or merchant distribution would be needed.</div>
  <div class="gap"><strong>Comparable competitor shares:</strong> I don’t know current, like-for-like 2024 shares for every named competitor. A current KFTC market study or library report using one market-share definition would be needed.</div>
  <div class="gap"><strong>Five-year forecast:</strong> I don’t know a defensible numeric 2025–2030 market forecast from the reviewed public sources. A dated market-research forecast with methodology and market definition would be needed.</div>
  <h3>Source register</h3><ol class="source-list">${Object.entries(sources).map(([id,s])=>`<li><strong>${id}: </strong><a href="${s.url}" target="_blank" rel="noopener">${esc(s.name)}</a><br><span class="meta">Find it at: ${esc(s.where)}</span></li>`).join('')}</ol>`;}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function markdown(){let out=`# ${brief.company} — ${brief.industry}\n\nMarket: ${brief.market}\n\n## Scope\n${brief.scope}\n\n## NAICS\n**${brief.naics}**\n\n${brief.naicsWhy}\n\n`;brief.signals.forEach(x=>out+=`## ${x.title}\n${x.text}\n\nSources: ${x.cite}\n\n`);out+='## Evidence gaps\n- Supplier concentration: I don’t know a verified ratio; need current supplier/merchant distribution data.\n- Comparable competitor shares: I don’t know current comparable shares for each platform; need KFTC or library market report.\n- Numeric five-year forecast: I don’t know one from reviewed public evidence; need forecast methodology.\n\n## Source register\n';Object.entries(sources).forEach(([id,s])=>out+=`- [${id}] ${s.name}. Find it at: ${s.where}. ${s.url}\n`);return out}
async function ingest(files){for(const file of files){try{$('#ingestStatus').textContent=`Preparing ${file.name}…`;const pdfApi=await getPdfJs();const pdf=await pdfApi.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let pages=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const content=await page.getTextContent();pages.push(content.items.map(i=>i.str).join(' '))}imported.push({name:file.name,pages});$('#reportList').innerHTML=imported.map(r=>`<div class="report"><strong>${esc(r.name)}</strong> — ${r.pages.length} pages extracted locally. <button data-report="${esc(r.name)}">Search evidence</button></div>`).join('');$('#ingestStatus').textContent=`${imported.length} report(s) ready. Add citations using the document name and page number returned by search.`}catch(e){imported.push({name:file.name,pages:[]});$('#reportList').innerHTML=imported.map(r=>`<div class="report"><strong>${esc(r.name)}</strong> — ${r.pages.length?`${r.pages.length} pages extracted locally.`:'Registered locally; page extraction needs an internet connection.'} <button data-report="${esc(r.name)}">Search evidence</button></div>`).join('');$('#ingestStatus').textContent=`${file.name} is registered. The rest of the pipeline remains available; use its visible page numbers for manual citations if extraction is unavailable.`}}}
$('#reports').addEventListener('change',e=>ingest(e.target.files));$('#reportList').addEventListener('click',e=>{if(!e.target.dataset.report)return;const term=prompt('Search this report for a word or phrase (for example: market share)');if(!term)return;const r=imported.find(x=>x.name===e.target.dataset.report);if(!r.pages.length){alert(`${r.name} is registered, but its text was not extracted. Use the report viewer's printed page number and cite: ${r.name}, p. [page].`);return}const hits=r.pages.map((t,i)=>t.toLowerCase().includes(term.toLowerCase())?i+1:null).filter(Boolean);alert(hits.length?`${r.name}: “${term}” appears on page(s) ${hits.join(', ')}. Cite as: ${r.name}, p. [page].`:'No page-level text match found. Try a shorter term.');});
$('#run').onclick=()=>{brief.company=$('#company').value.trim()||'Unnamed company';brief.market=$('#market').value.trim()||'Unspecified market';if(brief.company.toLowerCase()!=='coupang'){$('#status').textContent='Blank company context loaded. The included Coupang example remains the evidence model; replace each claim only after adding a findable source.'}else $('#status').textContent='Coupang example loaded: 8 cited signals, 3 explicit evidence gaps.';render()};$('#loadExample').onclick=()=>{brief.company='Coupang';brief.market='South Korea';$('#company').value='Coupang';$('#market').value='South Korea';$('#status').textContent='Coupang example loaded: 8 cited signals, 3 explicit evidence gaps.';render()};$('#downloadJson').onclick=()=>download('coupang-industry-brief.json',JSON.stringify({brief,competitors,sources,evidenceGaps:['Supplier concentration ratio not found','Current comparable individual competitor shares not found','Numeric five-year forecast not found']},null,2),'application/json');$('#downloadMd').onclick=()=>download('coupang-industry-brief.md',markdown(),'text/markdown');$('#print').onclick=()=>window.print();render();
